### ISSUE TITLE
Code for speech sythesis

### ISSUE THREAD

**Issue by yyua8222** [xi-j/Mamba-ASR#1]
Hi, thanks for the great work. Do we have any plan to publicise the code for speech synthesis?
Thanks

**Comment by xi-j** [comment]
Thanks for your interest. Unfortunately, we can't open-source our code since VALL-E is not open-sourced. 
You can refer to third-party implementation of VALL-E like https://github.com/lifeiteng/vall-e and replace MHSA with Mamba.
